/* FILE: public_html/database.sql */
CREATE TABLE IF NOT EXISTS csv_files (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    description TEXT,
    json_text LONGTEXT NOT NULL,
    row_count INT UNSIGNED NOT NULL DEFAULT 0,
    size_kb DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    file_uuid VARCHAR(10) UNIQUE NOT NULL DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_file_uuid (file_uuid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
